add support for downloading rootfs cache from server
enable by default

Signed-off-by: Nick Xie <nick@khadas.com>

diff --git a/config/functions/build-rootfs b/config/functions/build-rootfs
--- a/config/functions/build-rootfs
+++ b/config/functions/build-rootfs
@@ -203,137 +203,162 @@ create_rootfs_cache()
 	local packages_hash=$(get_package_list_hash)
 	local cache_fname=$BUILD_IMAGES/cache/rootfs/${DISTRIB_RELEASE}-${DISTRIB_TYPE}-${DISTRIB_ARCH}.$packages_hash.tar.lz4
 	local display_name=${DISTRIB_RELEASE}-${DISTRIB_TYPE}-${DISTRIB_ARCH}.${packages_hash:0:3}...${packages_hash:29}.tar.lz4
-	if [[ -f $cache_fname ]]; then
+	if [[ -f $cache_fname && -f ${cache_fname}.sha256 ]]; then
 		local date_diff=$(( ($(date +%s) - $(stat -c %Y $cache_fname)) / 86400 ))
-		info_msg "Extracting $display_name $date_diff days old"
-		# may be no need progress at all its very fast
-		lz4 -dc < $cache_fname | tar xp --xattrs -C $ROOTFS_TEMP/
-	else
-		info_msg "Creating new rootfs for $DISTRIB_RELEASE-$DISTRIB_TYPE"
+		# Check
+		local cache_sha256=$(cat ${cache_fname}.sha256)
+		local calc_sha256=$(sha256sum $cache_fname | cut -d" " -f1)
 
-		# stage: debootstrap base system
-		if [[ $NO_APT_CACHER != yes ]]; then
-			# apt-cacher-ng apt-get proxy parameter
-			local apt_extra="-o Acquire::http::Proxy=\"http://${APT_PROXY_ADDR:-localhost:3142}\""
-			local apt_mirror="http://${APT_PROXY_ADDR:-localhost:3142}/$APT_MIRROR"
+		if [[ $cache_sha256 == $calc_sha256 ]]; then
+			info_msg "Extracting $display_name $date_diff days old"
+			# may be no need progress at all its very fast
+			lz4 -dc < $cache_fname | tar xp --xattrs -C $ROOTFS_TEMP/
+
+			return
 		else
-			local apt_mirror="http://$APT_MIRROR"
+			warning_msg "Cache `basename $cache_fname` checksum not match! Clean up!"
+			rm $cache_fname  ${cache_fname}.sha256
 		fi
-
-		# fancy progress bars
-		[ "$NO_COLOR" -o "$NO_PROGRESS" ] || \
-		local apt_extra_progress="--show-progress -o DPKG::Progress-Fancy=1"
-
-		info_msg "Installing base system - Stage 1/2"
-		eval 'debootstrap --variant=minbase --include=${DEBOOTSTRAP_LIST// /,} ${PACKAGE_LIST_EXCLUDE:+ --exclude=${PACKAGE_LIST_EXCLUDE// /,}} \
-			--arch=$DISTRIB_ARCH --components=${DEBOOTSTRAP_COMPONENTS} --foreign $DISTRIB_RELEASE $ROOTFS_TEMP/ $apt_mirror'
-
-		[[ ${PIPESTATUS[0]} -ne 0 || ! -f $ROOTFS_TEMP/debootstrap/debootstrap ]] && error_msg "Debootstrap base system first stage failed" && return -1
-
-		cp /usr/bin/$QEMU_BINARY $ROOTFS_TEMP/usr/bin/
-
-		mkdir -p $ROOTFS_TEMP/usr/share/keyrings/
-		cp /usr/share/keyrings/debian-archive-keyring.gpg $ROOTFS_TEMP/usr/share/keyrings/
-		cp /usr/share/keyrings/ubuntu-archive-keyring.gpg $ROOTFS_TEMP/usr/share/keyrings/
-
-		info_msg "Installing base system - Stage 2/2"
-		eval 'chroot $ROOTFS_TEMP /bin/bash -c "/debootstrap/debootstrap --second-stage"'
-
-		[[ ${PIPESTATUS[0]} -ne 0 || ! -f $ROOTFS_TEMP/bin/bash ]] && error_msg "Debootstrap base system second stage failed" && return -1
-
-		mount_chroot "$ROOTFS_TEMP"
-
-		# policy-rc.d script prevents starting or reloading services during image creation
-		printf '#!/bin/sh\nexit 101' > $ROOTFS_TEMP/usr/sbin/policy-rc.d
-		chroot $ROOTFS_TEMP /bin/bash -c "dpkg-divert --quiet --local --rename --add /sbin/initctl"
-		chroot $ROOTFS_TEMP /bin/bash -c "dpkg-divert --quiet --local --rename --add /sbin/start-stop-daemon"
-		printf '#!/bin/sh\necho "Warning: Fake start-stop-daemon called, doing nothing"' > $ROOTFS_TEMP/sbin/start-stop-daemon
-		printf '#!/bin/sh\necho "Warning: Fake initctl called, doing nothing"' > $ROOTFS_TEMP/sbin/initctl
-		chmod 755 $ROOTFS_TEMP/usr/sbin/policy-rc.d
-		chmod 755 $ROOTFS_TEMP/sbin/initctl
-		chmod 755 $ROOTFS_TEMP/sbin/start-stop-daemon
-
-		# stage: configure language and locales
-		info_msg "Configuring locales $DEST_LANG"
-
-		[[ -f $ROOTFS_TEMP/etc/locale.gen ]] && sed -i "s/^# $DEST_LANG/$DEST_LANG/" $ROOTFS_TEMP/etc/locale.gen
-		eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "locale-gen $DEST_LANG"'
-		eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "update-locale LANG=$DEST_LANG LANGUAGE=$DEST_LANG LC_MESSAGES=$DEST_LANG"'
-
-		if [[ -f $ROOTFS_TEMP/etc/default/console-setup ]]; then
-			sed -e 's/CHARMAP=.*/CHARMAP="UTF-8"/' -e 's/FONTSIZE=.*/FONTSIZE="8x16"/' \
-				-e 's/CODESET=.*/CODESET="guess"/' -i $ROOTFS_TEMP/etc/default/console-setup
-			eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "setupcon --save"'
-		fi
-
-		# stage: create apt sources list
-		create_sources_list "$DISTRIB_RELEASE" "$ROOTFS_TEMP/"
-
-		# stage: install key
-		cp $CONFIG/fenix.key $ROOTFS_TEMP
-		eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "cat fenix.key | apt-key add -"'
-		rm $ROOTFS_TEMP/fenix.key
-
-		# compressing packages list to gain some space
-		echo "Acquire::GzipIndexes "true"; Acquire::CompressionTypes::Order:: "gz";" > $ROOTFS_TEMP/etc/apt/apt.conf.d/02compress-indexes
-		echo "Acquire::Languages "none";" > $ROOTFS_TEMP/etc/apt/apt.conf.d/no-languages
-
-		# add armhf arhitecture to arm64
-		if [[ $DISTRIB_ARCH == arm64 ]]; then
-			eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "dpkg --add-architecture armhf"'
-		fi
-
-		# this should fix resolvconf installation failure in some cases
-		chroot $ROOTFS_TEMP /bin/bash -c 'echo "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections'
-
-		# stage: update packages list
-		info_msg "Updating package list $DISTRIB_RELEASE"
-		eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "apt-get -y $apt_extra update"'
-
-		# stage: upgrade base packages from xxx-updates and xxx-backports repository branches
-		info_msg "Upgrading base packages"
-		eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -y \
-			$apt_extra $apt_extra_progress upgrade"'
-
-		# stage: install additional packages
-		info_msg "Installing packages"
-		eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -y \
-			$apt_extra $apt_extra_progress --no-install-recommends install $PACKAGE_LIST"' \
-
-		if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
-			error_msg "Installation of packages failed"
-			return -1
-		fi
-
-		[ "$DEBUG" ] && {
-		# DEBUG: print free space
-		echo -e "\nFree space:"
-		eval 'df -h'
-		}
-
-		# stage: remove downloaded packages
-		chroot $ROOTFS_TEMP /bin/bash -c "apt-get clean"
-
-		# this is needed for the build process later since resolvconf generated file in /run is not saved
-		rm $ROOTFS_TEMP/etc/resolv.conf
-		echo "nameserver $NAMESERVER" >> $ROOTFS_TEMP/etc/resolv.conf
-
-		# stage: make rootfs cache archive
-		info_msg "Ending debootstrap process and preparing cache $DISTRIB_RELEASE"
-		sync
-		# the only reason to unmount here is compression progress display
-		# based on rootfs size calculation
-		umount_chroot "$ROOTFS_TEMP"
-
-		if [ "$NO_PROGRESS" ]; then
-		    tar cp --xattrs --directory=$ROOTFS_TEMP/ --exclude='./dev/*' --exclude='./proc/*' --exclude='./run/*' --exclude='./tmp/*' \
-			--exclude='./sys/*' . | lz4 -c > $cache_fname
-		else
-		    tar cp --xattrs --directory=$ROOTFS_TEMP/ --exclude='./dev/*' --exclude='./proc/*' --exclude='./run/*' --exclude='./tmp/*' \
-			--exclude='./sys/*' . | pv -p -b -r -s $(du -sb $ROOTFS_TEMP/ | cut -f1) -N "$display_name" | lz4 -c > $cache_fname
-		fi
-		chmod 0777 $cache_fname
 	fi
+
+	if [ "$SKIP_ROOTFS_CACHE_DOWNLOAD" != "yes" ]; then
+		info_msg "Try to download cache from server"
+		if download_rootfs_cache $(basename $cache_fname); then
+			local date_diff=$(( ($(date +%s) - $(stat -c %Y $cache_fname)) / 86400 ))
+			info_msg "Extracting $display_name $date_diff days old"
+			# may be no need progress at all its very fast
+			lz4 -dc < $cache_fname | tar xp --xattrs -C $ROOTFS_TEMP/
+
+			return
+		fi
+	fi
+
+	info_msg "Creating new rootfs for $DISTRIB_RELEASE-$DISTRIB_TYPE"
+
+	# stage: debootstrap base system
+	if [[ $NO_APT_CACHER != yes ]]; then
+		# apt-cacher-ng apt-get proxy parameter
+		local apt_extra="-o Acquire::http::Proxy=\"http://${APT_PROXY_ADDR:-localhost:3142}\""
+		local apt_mirror="http://${APT_PROXY_ADDR:-localhost:3142}/$APT_MIRROR"
+	else
+		local apt_mirror="http://$APT_MIRROR"
+	fi
+
+	# fancy progress bars
+	[ "$NO_COLOR" -o "$NO_PROGRESS" ] || \
+	local apt_extra_progress="--show-progress -o DPKG::Progress-Fancy=1"
+
+	info_msg "Installing base system - Stage 1/2"
+	eval 'debootstrap --variant=minbase --include=${DEBOOTSTRAP_LIST// /,} ${PACKAGE_LIST_EXCLUDE:+ --exclude=${PACKAGE_LIST_EXCLUDE// /,}} \
+		--arch=$DISTRIB_ARCH --components=${DEBOOTSTRAP_COMPONENTS} --foreign $DISTRIB_RELEASE $ROOTFS_TEMP/ $apt_mirror'
+
+	[[ ${PIPESTATUS[0]} -ne 0 || ! -f $ROOTFS_TEMP/debootstrap/debootstrap ]] && error_msg "Debootstrap base system first stage failed" && return -1
+
+	cp /usr/bin/$QEMU_BINARY $ROOTFS_TEMP/usr/bin/
+
+	mkdir -p $ROOTFS_TEMP/usr/share/keyrings/
+	cp /usr/share/keyrings/debian-archive-keyring.gpg $ROOTFS_TEMP/usr/share/keyrings/
+	cp /usr/share/keyrings/ubuntu-archive-keyring.gpg $ROOTFS_TEMP/usr/share/keyrings/
+
+	info_msg "Installing base system - Stage 2/2"
+	eval 'chroot $ROOTFS_TEMP /bin/bash -c "/debootstrap/debootstrap --second-stage"'
+
+	[[ ${PIPESTATUS[0]} -ne 0 || ! -f $ROOTFS_TEMP/bin/bash ]] && error_msg "Debootstrap base system second stage failed" && return -1
+
+	mount_chroot "$ROOTFS_TEMP"
+
+	# policy-rc.d script prevents starting or reloading services during image creation
+	printf '#!/bin/sh\nexit 101' > $ROOTFS_TEMP/usr/sbin/policy-rc.d
+	chroot $ROOTFS_TEMP /bin/bash -c "dpkg-divert --quiet --local --rename --add /sbin/initctl"
+	chroot $ROOTFS_TEMP /bin/bash -c "dpkg-divert --quiet --local --rename --add /sbin/start-stop-daemon"
+	printf '#!/bin/sh\necho "Warning: Fake start-stop-daemon called, doing nothing"' > $ROOTFS_TEMP/sbin/start-stop-daemon
+	printf '#!/bin/sh\necho "Warning: Fake initctl called, doing nothing"' > $ROOTFS_TEMP/sbin/initctl
+	chmod 755 $ROOTFS_TEMP/usr/sbin/policy-rc.d
+	chmod 755 $ROOTFS_TEMP/sbin/initctl
+	chmod 755 $ROOTFS_TEMP/sbin/start-stop-daemon
+
+	# stage: configure language and locales
+	info_msg "Configuring locales $DEST_LANG"
+
+	[[ -f $ROOTFS_TEMP/etc/locale.gen ]] && sed -i "s/^# $DEST_LANG/$DEST_LANG/" $ROOTFS_TEMP/etc/locale.gen
+	eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "locale-gen $DEST_LANG"'
+	eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "update-locale LANG=$DEST_LANG LANGUAGE=$DEST_LANG LC_MESSAGES=$DEST_LANG"'
+
+	if [[ -f $ROOTFS_TEMP/etc/default/console-setup ]]; then
+		sed -e 's/CHARMAP=.*/CHARMAP="UTF-8"/' -e 's/FONTSIZE=.*/FONTSIZE="8x16"/' \
+			-e 's/CODESET=.*/CODESET="guess"/' -i $ROOTFS_TEMP/etc/default/console-setup
+		eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "setupcon --save"'
+	fi
+
+	# stage: create apt sources list
+	create_sources_list "$DISTRIB_RELEASE" "$ROOTFS_TEMP/"
+
+	# stage: install key
+	cp $CONFIG/fenix.key $ROOTFS_TEMP
+	eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "cat fenix.key | apt-key add -"'
+	rm $ROOTFS_TEMP/fenix.key
+
+	# compressing packages list to gain some space
+	echo "Acquire::GzipIndexes "true"; Acquire::CompressionTypes::Order:: "gz";" > $ROOTFS_TEMP/etc/apt/apt.conf.d/02compress-indexes
+	echo "Acquire::Languages "none";" > $ROOTFS_TEMP/etc/apt/apt.conf.d/no-languages
+
+	# add armhf arhitecture to arm64
+	if [[ $DISTRIB_ARCH == arm64 ]]; then
+		eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "dpkg --add-architecture armhf"'
+	fi
+
+	# this should fix resolvconf installation failure in some cases
+	chroot $ROOTFS_TEMP /bin/bash -c 'echo "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections'
+
+	# stage: update packages list
+	info_msg "Updating package list $DISTRIB_RELEASE"
+	eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "apt-get -y $apt_extra update"'
+
+	# stage: upgrade base packages from xxx-updates and xxx-backports repository branches
+	info_msg "Upgrading base packages"
+	eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -y \
+		$apt_extra $apt_extra_progress upgrade"'
+
+	# stage: install additional packages
+	info_msg "Installing packages"
+	eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -y \
+		$apt_extra $apt_extra_progress --no-install-recommends install $PACKAGE_LIST"' \
+
+	if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
+		error_msg "Installation of packages failed"
+		return -1
+	fi
+
+	[ "$DEBUG" ] && {
+	# DEBUG: print free space
+	echo -e "\nFree space:"
+	eval 'df -h'
+	}
+
+	# stage: remove downloaded packages
+	chroot $ROOTFS_TEMP /bin/bash -c "apt-get clean"
+
+	# this is needed for the build process later since resolvconf generated file in /run is not saved
+	rm $ROOTFS_TEMP/etc/resolv.conf
+	echo "nameserver $NAMESERVER" >> $ROOTFS_TEMP/etc/resolv.conf
+
+	# stage: make rootfs cache archive
+	info_msg "Ending debootstrap process and preparing cache $DISTRIB_RELEASE"
+	sync
+	# the only reason to unmount here is compression progress display
+	# based on rootfs size calculation
+	umount_chroot "$ROOTFS_TEMP"
+
+	if [ "$NO_PROGRESS" ]; then
+	    tar cp --xattrs --directory=$ROOTFS_TEMP/ --exclude='./dev/*' --exclude='./proc/*' --exclude='./run/*' --exclude='./tmp/*' \
+		--exclude='./sys/*' . | lz4 -c > $cache_fname
+	else
+	    tar cp --xattrs --directory=$ROOTFS_TEMP/ --exclude='./dev/*' --exclude='./proc/*' --exclude='./run/*' --exclude='./tmp/*' \
+		--exclude='./sys/*' . | pv -p -b -r -s $(du -sb $ROOTFS_TEMP/ | cut -f1) -N "$display_name" | lz4 -c > $cache_fname
+	fi
+	chmod 0777 $cache_fname
+	sha256sum $cache_fname | cut -d" " -f1 > ${cache_fname}.sha256
+	fix_perms ${cache_fname}.sha256
 }
 
 ## creates image file, partitions and fs
